# Generated by Django 5.1.4 on 2024-12-19 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesDetail',
            fields=[
                ('llid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm_name', models.CharField(max_length=255)),
                ('party_name', models.CharField(max_length=255)),
                ('party_mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_details', to='labour.labour')),
            ],
            options={
                'verbose_name': 'Party Detail',
                'verbose_name_plural': 'Parties Details',
                'ordering': ['party_name'],
            },
        ),
    ]
